### ISSUE TITLE
Clicking the "inbox" link at the left panel doesn't open the respective page

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-mail-settings#282]
I think it worked before but stopped since v13-beta got deployed. The "Mailbox" link at the top panel still works, so can be treated as a workaround.

![go-to-inbox](https://user-images.githubusercontent.com/1560781/81927951-280dc400-95ed-11ea-821d-09c8ea9ca24f.gif)

**Comment by vladimiry** [comment]
Recently released beta 14 also experiences this issue.

**Comment by dhoko** [comment]
:wave: Thanks @vladimiry for the feedback! We are not happy with this UX so we are working on better solution that will have your issue resolved at the same time. A way to hit 2 birds with 1 stone.

**Comment by vladimiry** [comment]
Hope you are not going to split these 4 apps into another 8 apps, similarly to what happened with web client v3 :)

**Comment by vladimiry** [comment]
Closing since the issue got resolved in beta 16.

**Comment by vladimiry** [comment]
I just realized that the issue is still there (see animated screenshot), so reopening.

![link issue](https://user-images.githubusercontent.com/1560781/85031590-89462b80-b187-11ea-8b04-6a6a43091854.gif)

**Comment by vladimiry** [comment]
Fixed in beta 20.
